"""drop transactions.payer_telegram_id

Revision ID: 114588e01583
Revises: ac9136b24ec0
Create Date: 2026-05-11 20:23:12.501104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114588e01583'
down_revision: Union[str, Sequence[str], None] = 'ac9136b24ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payer_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payer_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
