"""Regenerate ``scripts/name_data.py`` with a fresh pool of 1000 unique
female names.

Usage::

    env -i HOME="$HOME" \
      PATH="/Users/vasiliikletkin/.pyenv/versions/3.13.11/bin:/usr/bin:/bin" \
      /Users/vasiliikletkin/.pyenv/versions/3.13.11/bin/poetry run \
      python -m scripts.gen_names

Honors the same locale weights and surname probability as before. The
output file is committed — edit names by hand if you want to swap them.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

from faker import Faker
from faker.exceptions import UniquenessException

# Weights are tuned to per-locale unique pool sizes (Faker ships
# 80 / 379 / 1003 / 495 unique female first names). Pushing ru_RU above
# ~0.08 forces lots of surnames once its pool drains.
LOCALE_WEIGHTS: list[tuple[str, float]] = [
    ("ru_RU", 0.08),
    ("en_US", 0.32),
    ("de_DE", 0.40),
    ("sv_SE", 0.20),
]
LAST_NAME_PROBABILITY = 0.10
NAME_MAX_LENGTH = 50  # matches src.domain.profile.value_objects.Name.MAX_LENGTH


def build_name_pool(target_count: int, seed: int) -> list[str]:
    """Return ``target_count`` globally-unique female names, shuffled."""
    random.seed(seed)
    fakers: dict[str, Faker] = {loc: Faker(loc) for loc, _ in LOCALE_WEIGHTS}
    for f in fakers.values():
        f.seed_instance(seed)

    allocations = {loc: int(target_count * w) for loc, w in LOCALE_WEIGHTS}
    leftover = target_count - sum(allocations.values())
    allocations["de_DE"] += leftover

    seen: set[str] = set()
    by_locale: dict[str, list[str]] = {loc: [] for loc, _ in LOCALE_WEIGHTS}
    for loc, _ in LOCALE_WEIGHTS:
        faker = fakers[loc]
        for _ in range(allocations[loc] * 4):
            if len(by_locale[loc]) >= allocations[loc]:
                break
            try:
                fn = faker.unique.first_name_female()
            except UniquenessException:
                break
            if fn in seen:
                continue
            seen.add(fn)
            by_locale[loc].append(fn)

    deficit = target_count - sum(len(v) for v in by_locale.values())
    if deficit > 0:
        for loc, _ in LOCALE_WEIGHTS:
            faker = fakers[loc]
            while deficit > 0:
                try:
                    fn = faker.unique.first_name_female()
                except UniquenessException:
                    break
                if fn in seen:
                    continue
                seen.add(fn)
                by_locale[loc].append(fn)
                deficit -= 1
            if deficit == 0:
                break

    pairs: list[tuple[str, str]] = []
    for loc, names in by_locale.items():
        pairs.extend((n, loc) for n in names)
    if len(pairs) < target_count:
        raise RuntimeError(
            f"Could not assemble {target_count} unique first names; "
            f"only got {len(pairs)}."
        )

    random.shuffle(pairs)
    pairs = pairs[:target_count]

    n_with_surname = round(target_count * LAST_NAME_PROBABILITY)
    surname_idx = set(random.sample(range(target_count), n_with_surname))

    full_names: list[str] = []
    full_seen: set[str] = set()
    for i, (first, loc) in enumerate(pairs):
        if i in surname_idx:
            last = fakers[loc].last_name_female()
            candidate = f"{first} {last}"[:NAME_MAX_LENGTH]
            while candidate in full_seen:
                last = fakers[loc].last_name_female()
                candidate = f"{first} {last}"[:NAME_MAX_LENGTH]
        else:
            candidate = first[:NAME_MAX_LENGTH]
        full_seen.add(candidate)
        full_names.append(candidate)

    random.shuffle(full_names)
    return full_names


_OUTPUT_HEADER = '''# ruff: noqa: RUF001  # intentional Cyrillic in some names
"""Static pool of 1000 unique female names for seeded profiles.

Generated by ``scripts/gen_names.py`` (uses Faker with locales
ru_RU + en_US + de_DE + sv_SE). Edit by hand if you want to swap
specific entries — order does not matter, the seed script just iterates
the list and indexes by profile number.

Stats: ~80 Cyrillic + ~920 Latin; exactly 10% of entries include a
surname. To regenerate, run::

    poetry run python -m scripts.gen_names
"""

from __future__ import annotations

FEMALE_NAMES: list[str] = [
'''


def write_name_data(names: list[str], output: Path) -> None:
    lines = [_OUTPUT_HEADER]
    for n in names:
        escaped = n.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",\n')
    lines.append("]\n")
    output.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=20260512)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent / "name_data.py",
    )
    args = parser.parse_args()

    names = build_name_pool(args.count, args.seed)
    write_name_data(names, args.output)
    cyrillic = sum(
        1 for n in names if any(0x0400 <= ord(c) <= 0x04FF for c in n)
    )
    with_surname = sum(1 for n in names if " " in n)
    print(
        f"Wrote {len(names)} names to {args.output} "
        f"(cyrillic={cyrillic}, with_surname={with_surname})."
    )


if __name__ == "__main__":
    main()
