# ruff: noqa: RUF001  # intentional Cyrillic in some names
"""Static pool of 1000 unique female names for seeded profiles.

Generated once by ``scripts/gen_names.py`` (uses Faker with locales
ru_RU + en_US + de_DE + sv_SE). Edit by hand if you want to swap
specific entries — order does not matter, the seed script just iterates
the list and indexes by profile number.

Stats: ~80 Cyrillic + ~920 Latin; exactly 100 entries include a surname
(10%). To regenerate, run::

    poetry run python -m scripts.gen_names

"""

from __future__ import annotations

FEMALE_NAMES: list[str] = [
    "Krystal",
    "Britt-Marie",
    "Friedlinde Schönland",
    "Zita",
    "Lise-Lotte",
    "Constance",
    "Theresa",
    "Melita",
    "Ann-Marie",
    "Evelina",
    "Angel",
    "Hanna",
    "Christin",
    "Pia",
    "Victoria",
    "Eva",
    "Valborg Lundell",
    "Таисия",
    "Melissa",
    "Faith",
    "Notburga",
    "Connie",
    "Karina",
    "Eveline",
    "Antoinette",
    "Candice",
    "Carmela",
    "Liesbeth",
    "Janice Perkins",
    "Sybilla",
    "Amelia",
    "Elly",
    "Tara Nolan",
    "Diana",
    "Canan",
    "Lori",
    "Tammy",
    "Gunvor Olsson",
    "Антонина",
    "Marianne",
    "Mirjam",
    "Monica",
    "Inka",
    "Wilma Kensy",
    "Ines",
    "Catharina",
    "Lisbeth Isaksson",
    "Käthe",
    "Анжела",
    "Marjan",
    "Friedl",
    "Sophie Klingelhöfer",
    "Мария",
    "Gunborg",
    "Прасковья",
    "Ina",
    "Carol",
    "Агата",
    "Yasmin",
    "Глафира",
    "Mallory",
    "Mariechen",
    "Вероника",
    "Hertha Hertrampf",
    "Elinor",
    "Terry",
    "Siegrid",
    "Lucie",
    "Maj-Britt",
    "Liselott",
    "Bettina",
    "Myriam",
    "Jennifer",
    "Lynn",
    "Cathrin",
    "Mohammed",
    "Emmi",
    "Irmtraud Gotthard",
    "Joanna",
    "Marlene",
    "Viktoria Löffler",
    "Kerry Delacruz",
    "Engla Svensson",
    "Violetta",
    "Ольга",
    "Maryam",
    "Miriam",
    "Nicole",
    "Georgine",
    "Anni",
    "Leni",
    "Edit",
    "Elsie",
    "Элеонора",
    "Alexa",
    "Betty",
    "Rotraut",
    "Tanya",
    "Mirjana",
    "Luna",
    "Minna Berglund",
    "Lisbet",
    "Maria",
    "Kelly",
    "Sibylla",
    "Jeanette",
    "Reinhilde",
    "Carin",
    "Zenta",
    "Luitgard",
    "Надежда",
    "Monika",
    "Октябрина Турова",
    "Ester",
    "Майя",
    "Rosa-Maria",
    "Gunilla Gustavsson",
    "Лидия",
    "Gönül",
    "Jocelyn",
    "Bodil",
    "Julie",
    "Meghan",
    "Carolyn",
    "Senta",
    "Christel",
    "Фаина",
    "Birte",
    "Ilonka",
    "Alyssa",
    "Philomena",
    "Cora",
    "Veronica",
    "Ariane",
    "Wally",
    "Jane",
    "Ingela",
    "Феврония",
    "Rose",
    "Nora",
    "Maarit",
    "Laura Allen",
    "Anette",
    "Yasemin",
    "Mariann",
    "Linnéa",
    "Sanna",
    "Татьяна",
    "Gerd",
    "Ebba Åberg",
    "Marit",
    "Andrea",
    "Agathe",
    "Helga",
    "Henny",
    "Danielle",
    "Waltrud",
    "Sigrid",
    "Gina",
    "Lissi Meyer",
    "Kaylee",
    "Becky",
    "Natalija",
    "Rachael",
    "Janet",
    "Colleen",
    "Marlies",
    "Kristine",
    "Valerie",
    "Elin",
    "Agnes",
    "Ethel",
    "Evamaria",
    "Annelene",
    "Gerda",
    "Kläre",
    "Samantha",
    "Britt Karge",
    "Jillian",
    "Leona",
    "Yvette",
    "Sierra",
    "Martina",
    "Irmtrud Gorlitz",
    "Imelda",
    "Gunnel",
    "Frieda",
    "Dunja",
    "Rosmarie",
    "Sabina",
    "Heidelore Schaaf",
    "Варвара",
    "Jaclyn Smith",
    "Brita",
    "Eleonor",
    "Alice",
    "Jasmin Thompson",
    "Kornelia Römer",
    "Bruni",
    "Miroslawa",
    "Eira",
    "Annelie",
    "Sheryl",
    "Sue",
    "Janina",
    "Nurten",
    "Karen",
    "Jeannine",
    "Kirsten",
    "Emilia",
    "Ann-Kristin Singh",
    "Klara",
    "Alexandra",
    "Rabea",
    "Hedi",
    "Madeline",
    "Lotta",
    "Matilda Blomberg",
    "Sherri Wilson",
    "Carina",
    "Josefine Dahlén",
    "Ursula",
    "Harriet",
    "Britta",
    "Sofie",
    "Hilda Boström",
    "Ludmilla",
    "Анастасия",
    "Stilla",
    "Marianna Pergande",
    "Augusta",
    "Maj",
    "Barbara",
    "Edeltrud Stumpf",
    "Uta",
    "Marie-Louise",
    "Kendra Powers",
    "Aleksandra",
    "Darlene",
    "Elisabeth",
    "Bailey",
    "Doreen",
    "Gerlinde",
    "Kari",
    "Karolina",
    "Lidia",
    "Tina",
    "Rhonda",
    "Elna",
    "Sina",
    "Åsa Karlsson",
    "Linn",
    "Ann-Sofie Persson",
    "Justina",
    "Liliane Schenk",
    "Sophia Riley",
    "Dorothee",
    "Erna",
    "Stina",
    "Валерия",
    "Валентина",
    "Martine Gude",
    "Elisa",
    "Sonja",
    "Vicki",
    "Teresia",
    "Sharon",
    "Mariana",
    "Kristy",
    "Joanne",
    "Irma",
    "Sylwia",
    "Signe",
    "Mohamed",
    "April",
    "Latoya",
    "Алла",
    "Leena",
    "Ronja",
    "Cindy",
    "Ульяна",
    "Людмила",
    "Tonya",
    "Jeanne",
    "Margit Öberg",
    "Ortrun",
    "Susann",
    "Suse",
    "Johanne",
    "Miranda",
    "Selena",
    "Hanne-Lore",
    "Mina",
    "Eugenia",
    "Elfi",
    "Раиса",
    "Erika",
    "Ljiljana Dörr",
    "Ann-Charlotte",
    "Wenke",
    "Lovisa",
    "Marilyn",
    "Lia Geißler",
    "София",
    "Deborah",
    "Silvana",
    "Pernilla",
    "Gesche",
    "Kata",
    "Lea",
    "Dagmar Weimer",
    "Виктория",
    "Felicia",
    "Nadia",
    "Cecilia",
    "Madlen",
    "Gertraut",
    "Elizabeth",
    "Meryem",
    "Paige",
    "Зоя",
    "Gudrun Rosemann",
    "Jessica",
    "Elsa",
    "Olena",
    "Ingegerd",
    "Florentine",
    "Heidi",
    "Katherine Wright",
    "Anne-Rose",
    "Janett",
    "Debbie Watts",
    "Марина Колесникова",
    "Ida",
    "Ingelore",
    "Вера",
    "Luisa",
    "Alicia",
    "Louise",
    "Tove",
    "Kristi",
    "Robyn Olsen",
    "Melina",
    "Kordula",
    "Anne-Katrin",
    "Leah",
    "Tabea",
    "Gülten",
    "Иванна",
    "Ann-Kathrin",
    "Kira",
    "Alma",
    "Frauke",
    "Lisa",
    "Berta",
    "Hannah",
    "Любовь",
    "Алина",
    "Radmila",
    "Marisa",
    "Kathi Adolph",
    "Mari",
    "Friedhilde",
    "Eivor",
    "Gusti Ladeck",
    "Del",
    "Алевтина",
    "Агафья",
    "Marlis",
    "Caitlin",
    "Morgan",
    "Inga",
    "Theda",
    "Kriemhild",
    "Denise",
    "Marita",
    "Makayla",
    "Dagny",
    "Romana",
    "Arzu",
    "Wendelin",
    "Adina Rogner",
    "Ulrika Holm",
    "Anna",
    "Siv Eliasson",
    "Shirley",
    "Cilly Schleich",
    "Linda",
    "Marliese",
    "Gerta",
    "Sofia",
    "Jasmina",
    "Olivia",
    "Anja",
    "Valentina",
    "Teresa",
    "Gloria",
    "Christina",
    "Ylva",
    "Brianna Silva",
    "Ebony",
    "Регина",
    "Анна",
    "Madelene",
    "Brandy",
    "Grace",
    "Virginia",
    "Jutta",
    "Sieglinde",
    "Michelle Horn",
    "Gaby",
    "Angelica",
    "Angelika",
    "Jenna",
    "Danica",
    "Kristie",
    "Inna Mangold",
    "Autumn",
    "Christl",
    "Marieluise",
    "Оксана",
    "Katerina",
    "Kristen",
    "Angela",
    "Marie",
    "Gertraude",
    "Ewa",
    "Lisette",
    "Wanda",
    "Chelsea",
    "Alexis",
    "Maria-Theresia",
    "Lillemor",
    "Carolina",
    "Маргарита",
    "Hilde",
    "Annelies",
    "Margaretha",
    "Holly",
    "Natalja Ullrich",
    "Janna",
    "Галина",
    "Livia",
    "Ingeborg",
    "Deanna",
    "Donna",
    "Priscilla",
    "Carola",
    "Rotraud",
    "Trudel",
    "Annelore",
    "Jade Reed",
    "Paulina",
    "Felizitas",
    "Amber Hamilton",
    "Verena Zobel",
    "Casey",
    "Dorothy",
    "Whitney",
    "Elzbieta",
    "Natasha",
    "Martha",
    "Meagan",
    "Claire",
    "Mirja",
    "Antonietta Schinke",
    "Sherry Hall",
    "Anneliese",
    "Trude",
    "Rebekah",
    "Gundi",
    "Barbro",
    "Nichole",
    "Stella",
    "Ashley",
    "Kajsa Nordström",
    "Rosa",
    "Gabrielle",
    "Евгения",
    "Aina Karlsson",
    "Stacy",
    "Heather",
    "Elwira",
    "Sarah",
    "Candace",
    "Lina",
    "Nevenka Trub",
    "Bonnie",
    "Telse Sorgatz",
    "Waldtraut",
    "Jody",
    "Luzie",
    "Paula",
    "Silvia",
    "Hubertine",
    "Rebecca",
    "Maya",
    "Vilhelmina",
    "Belinda",
    "Mackenzie",
    "Sylke",
    "Gertrud",
    "Ira",
    "Jordan",
    "Courtney",
    "Leslie",
    "Meike",
    "Carmine",
    "Hermine",
    "Reinhild",
    "Clarissa",
    "Elina",
    "Lena Karlsson",
    "Frida",
    "Breanna",
    "Tilde",
    "Mariah",
    "Laurie",
    "Auguste",
    "Gerhild",
    "Christy",
    "Зинаида",
    "Aurora",
    "Hedda",
    "Gisela",
    "Melanie",
    "Monique",
    "Дарья",
    "Hannchen",
    "Adriana",
    "Светлана",
    "Лукия",
    "Anika",
    "Sara",
    "Hilma",
    "Brittney",
    "Эмилия",
    "Elena",
    "Betina Hornig",
    "Mary",
    "Inga-Lill",
    "Berit",
    "Catrin",
    "Norma",
    "Alwina",
    "Gesa",
    "Sonya",
    "Inge",
    "Destiny",
    "Walentina",
    "Marcia Bauer",
    "Nadine",
    "Simone",
    "Swantje",
    "Sandy",
    "Heidrun",
    "Christiane",
    "Nathalie",
    "Shelia",
    "Haley Reyes",
    "Charlotte",
    "Helén",
    "Leonore",
    "Viola",
    "Irina Geisel",
    "Taylor Caldwell",
    "Jonna",
    "Karla",
    "Semra",
    "Terri",
    "Ivonne",
    "Наина",
    "Dawn",
    "Claudia",
    "Margrit",
    "Joan",
    "Petra",
    "Edeltraut",
    "Simona",
    "Ann-Sofi",
    "Susan",
    "Ingalill",
    "Isabella",
    "Лора",
    "Nadeshda",
    "Waltraut Süßebier",
    "Hillevi",
    "Fatma",
    "Жанна",
    "Bianca",
    "Malin",
    "Bertha",
    "Renee",
    "Edeltraud",
    "Ortrud",
    "Crystal",
    "Клавдия",
    "Diane",
    "Sandra",
    "Käte",
    "Megan",
    "Magdalena",
    "Gilda",
    "Traci",
    "Lindsey",
    "Ilka",
    "Luka",
    "Geraldine",
    "Sheri",
    "Julia",
    "Debra",
    "Josefin",
    "Magrit",
    "Ingrid",
    "Bianka Karge",
    "Dana",
    "Ella",
    "Peggy",
    "Misty",
    "Chloe",
    "Tami",
    "Theresia",
    "Märta",
    "Bernadette",
    "Mareile",
    "Пелагея",
    "Jasmine",
    "Shawna",
    "Veronique",
    "Loni",
    "Lidwina",
    "Liesel",
    "Ivanka",
    "Suzanne",
    "Ragnhild",
    "Marina Seifert",
    "Wilhelmina",
    "Kristina",
    "Michele",
    "Aneta",
    "Dorina",
    "Audrey",
    "Ксения",
    "Gitte",
    "Shari Gordon",
    "Gordana",
    "Ellinor",
    "Penny",
    "Marta Winkler",
    "Марфа",
    "Kerstin",
    "Li",
    "Heide-Marie",
    "Ljudmila",
    "Giovanna",
    "Yvonne",
    "Vanessa",
    "Anna-Lena",
    "Ann-Louise",
    "Catarina",
    "Lieschen",
    "Manuela",
    "Linnea",
    "Madeleine",
    "Marissa",
    "Елизавета",
    "Gülay",
    "Rosel",
    "Ulrike",
    "Emily",
    "Ираида",
    "Dina",
    "Gabi",
    "Tricia",
    "Birgit",
    "Margareta",
    "Annie",
    "Ann-Christin",
    "Евфросиния",
    "Hanife",
    "Svenja",
    "Heiderose Barth",
    "Jennie",
    "Tiffany",
    "Cassandra",
    "Malva",
    "Zofia",
    "Songül",
    "Astrid",
    "Amanda",
    "Mathilde",
    "Evelyn",
    "Toni",
    "Emma",
    "Albertine",
    "Molly",
    "Krista",
    "Inez",
    "Helen",
    "Ирина Якушева",
    "Милица",
    "Sylvana",
    "Charlene",
    "Ruthild",
    "Mira",
    "Kara",
    "Gabriella",
    "Corina",
    "Janette",
    "Iréne",
    "Dorothea",
    "Yolanda",
    "Traude",
    "Herma",
    "Jill",
    "Emmy",
    "Maureen",
    "Ursel",
    "Kathleen",
    "Jackie",
    "Regina",
    "Jaime",
    "Ангелина",
    "Anka",
    "Isabel",
    "Kunigunde",
    "Anneli",
    "Annica",
    "Tilda",
    "Lise-Lott Pettersson",
    "Olga",
    "Rita",
    "Beverly",
    "Inger",
    "Margarete",
    "Nelli",
    "Margaret",
    "Marija",
    "Eleonore",
    "Solveig",
    "Shelly",
    "Elvira",
    "Katelyn",
    "Anneke",
    "Cathy",
    "Greta",
    "Kristin",
    "Carla Adams",
    "Johanna",
    "Hanne",
    "Nadja",
    "Jamie",
    "Gunda",
    "Kelsey",
    "Hayley",
    "Valentine",
    "Trudi",
    "Else",
    "Vanja",
    "Ayten",
    "Nancy",
    "Katarina",
    "Stephanie",
    "Anna-Karin Abbas",
    "Regine",
    "Евпраксия",
    "Cheryl",
    "Ariel",
    "Irene",
    "Fredrika",
    "Mathilda",
    "Zehra",
    "Dorota",
    "Lieselotte",
    "Dörte",
    "My",
    "Sydney",
    "Ellen",
    "Rosalinde",
    "Олимпиада",
    "Kaitlyn",
    "Carly",
    "Наталья",
    "Natalie",
    "Лариса",
    "Nelly",
    "Фёкла",
    "Helena Zahn",
    "Ilona Gotthard",
    "Abdi",
    "Tyra",
    "Stacey",
    "Wendy",
    "Нонна",
    "Тамара",
    "Ernestine",
    "Loretta Martinez",
    "Ayse Kraushaar",
    "Nadin",
    "Кира",
    "Roswitha",
    "Maja",
    "Fanny",
    "Agneta",
    "Madison",
    "Zdenka",
    "Sheila",
    "Gretl Möchlichen",
    "Emine",
    "Cosima",
    "Freya",
    "Cilli",
    "Magda",
    "Rahel",
    "Daisy",
    "Kaitlin",
    "Tracie",
    "Krystyna",
    "Kathy",
    "Tamara",
    "Sylvia",
    "Jacqueline",
    "Katrina",
    "Margret",
    "Marie-Therese",
    "Saskia",
    "Vera",
    "Meredith",
    "Евдокия",
    "Caroline",
    "Tracey",
    "Waltraud",
    "Clara",
    "Robin Smith",
    "Tasha",
    "Karin",
    "Savannah",
    "Синклитикия",
    "Fatima",
    "Allison",
    "Brittany",
    "Kylie",
    "Joyce",
    "Adriane",
    "Hedvig",
    "Полина",
    "Mona",
    "Emelie",
    "Lilian",
    "Doris",
    "Majken",
    "Cornelia",
    "Anita",
    "Lydia",
    "Camilla",
    "Carrie",
    "Kerri",
    "Василиса",
    "Sally",
    "Therese",
    "Rose-Marie",
    "Annette",
    "Hiltrud Schäfer",
    "Елена",
    "Heide",
    "Ria",
    "Christine Wilson",
    "Milla",
    "Oda",
    "Erica",
    "Brunhilde",
    "Anne",
    "Анжелика",
    "Svea",
    "Lissy",
    "Brenda",
    "Annemarie",
    "Rachel",
    "Amy",
    "Dietlinde",
    "Aysel",
    "Melinda",
    "Ludmila",
    "Ия",
    "Evi",
    "Catherine Nelson",
    "Юлия Мамонтова",
    "Anny",
    "Moa",
    "Beatrice",
    "Judith",
    "Erin",
    "Margarethe",
    "Susanne",
    "Dominique",
    "Lacey",
    "Elisabet",
    "Anica",
    "Antonia",
    "Judy",
    "Hannele",
    "Beate",
    "Birgitta",
    "Lorraine",
    "Irmgard",
    "Heidemarie",
    "Ann-Britt",
    "Pamela Parker",
    "Ruth",
    "Henri",
    "Shannon",
    "Michaela",
    "Alison",
    "Briana",
    "Svetlana",
    "Lindsay",
    "Ana Duncan",
    "Ann",
    "Nanna",
    "Agatha",
    "Sabrina Hutchinson",
    "Kayla",
    "Elise",
    "Anna-Maria",
    "Katie",
    "Kathryn",
    "Thea",
    "Selma Sandberg",
    "Александра",
    "Susana",
    "Lilly",
    "Jenny",
    "Екатерина",
    "Ellie",
    "Anna-Luise",
    "Isolde",
    "Mia",
    "Акулина Анисимова",
    "Marga",
    "Reingard",
    "Gun",
    "Janin",
    "Ehrentraud",
    "Freja",
    "Liesa Zorbach",
    "Shelby",
    "Tracy",
    "Helene",
    "Нина",
    "Siegrun",
    "Magdalene",
    "Janine",
    "Larissa",
    "Magarete",
    "Lauren",
    "Ulla",
    "Cynthia",
    "Patricia",
    "Käthi",
    "Elfie",
    "Gunhild",
    "Charlotta",
    "Tuva",
    "Beata",
    "Brooke",
    "Nuran",
    "Kim",
    "Desiree",
    "Carmen",
    "Sigrun",
    "Gudula",
    "Michaele",
    "Beth",
    "Нинель",
    "Mariele",
    "Cristina",
    "Esther",
    "Marjatta",
    "Susanna",
    "Marica",
    "Iris",
    "Hülya",
    "Jean",
    "Fabienne",
    "Wilfriede",
    "Olav",
    "Gun-Britt",
    "Evy",
    "Pauline",
    "Rut",
    "Margot",
    "Swetlana",
    "Nina",
    "Therése",
    "Gail",
    "Annika",
    "Frances Parker",
    "Abigail Richards",
    "Brandi",
    "Kimberly",
]
